DATA:
  DATASET:
    NAME: cub
    DROP_RATE: 0.4

TRAIN:
  SIM_GWEIGHTS: 0.5
  STAGE2:
    MAX_EPOCHS: 100
    WARMUP_EPOCHS: 10
    WEIGHT_DECAY: 1e-4
    BASE_LR: 5e-3
    WARMUP_LR: 5e-5
    MIN_LR: 5e-6
    OPTIMIZER:
      PARAMS: "lr = 5e-3; weight_decay = 1e-4; eps = 1e-8; betas = (0.9, 0.999)"
